config/routes.rb
Lojadecarros::Application.routes.draw do
  devise_for :users

  match 'carros/feed(.:format)' => 'carros#feed', :as => 'feed'
  match 'carros/busca' => 'carros#busca'
  resources :carros
  root :to => "carros#index"	

end

app/models/carro.rb
class Carro < ActiveRecord::Base
	def novo?
		true
	end

	def calcula_comissao
		preco * 0.05
	end

	define_index do
		indexes nome, :sortable => true

		has descricao, preco, created_at, updated_at
		set_property :delta => true
	end
end

app/models/carro_observer.rb
class CarroObserver < ActiveRecord::Observer

	def after_create(carro)
		Notifier.novo_carro(carro, "seu_email").deliver
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  def set_locale
  	session[:locale] = params[:locale] if params[:locale]
  	I18n.locale = session[:locale]
  end
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
	respond_to :rss, :only => :feed
	caches_page :index
	cache_sweeper :carro_sweeper

	def index
		@carro  = Carro.new
		@carros = Carro.order('created_at DESC').paginate :page => params[:page],
														  :per_page => 3
	end

	def create
		carro = Carro.new(params[:carro])
		carro.save
		redirect_to :action => "index"
	end

	def busca
		@query = params[:busca]		
		@carro = Carro.new
		@carros = Carro.search @query, :page 	  => params[:page],
									   :per_page  => 3,
									   :order 	  => :created_at,
									   :sort_mode => :desc
		render :action => 'index'
	end

	# outras actions
	def feed
		@carros = Carro.all

		respond_with @carros
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def hora_agora
		uri = 'http://developer.yahooapis.com/TimeService/V1/getTime'
		resposta = Restfulie.at(uri).get(:appid => 'YahooDemo')
		yahoo_time = resposta.resource['Result']['Timestamp'].to_i
		Time.at(yahoo_time).strftime("%d/%m/%Y %H:%M")
	end
end

app/helpers/carros_helper.rb
module CarrosHelper
	def num_formatado(obj)
		number_to_currency(obj, :precision => 2, :unit => "R$ ", :separator => ".", :delimiter => ",")
	end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/carros/_form.html.erb
<%= form_for(@carro) do |f| %>
  <% if @carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% @carro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing carro</h1>

<%= render 'form' %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<% if current_user %>

	<div id="form">
		<%= form_for @carro, :url => { :action => 'create' } do |f| -%>

		<strong>Quer vender ?</strong>
		<br /><br />

		<%= f.label :nome %><br />
		<%= f.text_field :nome, :class => 'button-input' %>
		<br />

		<%= f.label :descricao %><br />
		<%= f.text_area :descricao, :cols => 26, :rows => 9 %>
		<br />

		<%= f.label :preco %><br />
		<%= f.text_field :preco, :class => 'button-input' %>
		<br />

		<%= f.submit 'Anunciar!', :disable_with => '...', :class => 'anunciar' %>

		<% end -%>
	</div>
<% else %>
	Para cadastrar faça o login! <%= link_to 'Login', '/users/sign_in' %>
<% end %>

<div style="clear:both"></div>

<br />

<div id="busca">
	<strong>Carros a venda</strong>
	<br /><br />
	<%= form_tag :controller => 'carros', :action => 'busca' do %>
		<%= text_field_tag 'busca', nil, :class => 'button-search' %>
		<%= submit_tag "busca", :disable_with => "...", :class => 'buscar' %>
	<% end %>

	<% unless @carros.blank? %>
		<% @carros.each do |carro| %>
			<br />
			<b><%= carro.nome %></b><br />
			<%= carro.descricao %><br />
			<%= num_formatado(carro.preco) %><br />
		<% end %>
	<% else %>
		<p>Nenhum carro cadastrado.</p>
	<% end %>
</div>

<%= will_paginate @carros %>

app/views/carros/new.html.erb
<h1>New carro</h1>

<%= render 'form' %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application", :cache => true %>
    <%= javascript_include_tag :defaults, :cache => true %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


      <%= link_to 'US', root_path(:locale => 'en') %>
      <%= link_to 'PT', root_path(:locale => 'pt') %>
      <%= link_to 'RSS', feed_path('rss') %>

      <%# flash.each do |name, msg| %>
        <%#= content_tag :div, msg, :id => "flash_#{name}" %>
      <%# end %>


       <% if current_user %>
        <% link_to 'Logout', '/users/sign_out' %>
       <% end %>

      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
    <div id="footer" class="blue-style">
      <p>Loja de Carros | Caelum | Ruby on Rails | RR-75 | 2009</p>
      <p><%#= hora_agora %></p>
      <p><%= Info.texto %></p>
    </div>
	 <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/notifier/novo_carro.html.erb
Novo carro cadastrado!
<%= @carro.nome %>
<%= @carro.descricao %>
<%= @carro.preco %>